// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddShell(arg1:string):Promise<main.Pane>;

export function Branches():Promise<Array<string>>;

export function Checkout(arg1:string,arg2:string):Promise<string>;

export function Close(arg1:string):Promise<void>;

export function Create(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DefaultBase():Promise<string>;

export function DeleteBranch(arg1:string,arg2:string):Promise<string>;

export function Open(arg1:string):Promise<Array<main.Pane>>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Reload():Promise<main.Snapshot>;

export function Remove(arg1:string,arg2:boolean):Promise<string>;

export function Size(arg1:string,arg2:number,arg3:number):Promise<void>;

export function State():Promise<main.Snapshot>;

export function TakeInitial():Promise<string>;

export function Write(arg1:string,arg2:string):Promise<void>;
