// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branches() {
  return window['go']['main']['App']['Branches']();
}

export function Checkout(arg1, arg2) {
  return window['go']['main']['App']['Checkout'](arg1, arg2);
}

export function Close(arg1) {
  return window['go']['main']['App']['Close'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function Create(arg1, arg2, arg3) {
  return window['go']['main']['App']['Create'](arg1, arg2, arg3);
}

export function DefaultBase() {
  return window['go']['main']['App']['DefaultBase']();
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function NewTab(arg1, arg2) {
  return window['go']['main']['App']['NewTab'](arg1, arg2);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function OpenRepo() {
  return window['go']['main']['App']['OpenRepo']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function Remove(arg1, arg2) {
  return window['go']['main']['App']['Remove'](arg1, arg2);
}

export function SeenTab(arg1) {
  return window['go']['main']['App']['SeenTab'](arg1);
}

export function Size(arg1, arg2, arg3) {
  return window['go']['main']['App']['Size'](arg1, arg2, arg3);
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function TabBusy(arg1) {
  return window['go']['main']['App']['TabBusy'](arg1);
}

export function TakeInitial() {
  return window['go']['main']['App']['TakeInitial']();
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}
